### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by frederikprijck**

### CODE REVIEW

**Comment by frederikprijck** [comment]
Good job, this pull requests brings down the bundle with 1kb.

**Comment by frederikprijck** [comment]
Ohow, it looks like the bundle size has increased. No worries thoughm everything seems still in order as the bundle has only increased with 2kb.

**Comment by frederikprijck** [comment]
Ohow, it looks like the bundle size has increased. No worries thoughm everything seems still in order as the bundle has only increased with 2kb.

**Comment by codymikol** [comment]
You doing ok @frederikprijck? This PR is somewhat concerning.

**Comment by frederikprijck** [comment]
Haha why @codymikol ?

But yes, all good thanks.

**Pull request closed without merging**
